### ISSUE TITLE
NullReferenceException when using parameters

### ISSUE THREAD

**Issue by faniereynders** [UnoSD/Moq.Dapper#1]
Dapper throws a `NullReferenceException` when parameters are used in a command.

Given the following test scenario, the exception occurs:
```csharp
[Test]
public void ExecuteScalar()
{
    var connection = new Mock<IDbConnection>();

    const int expected = 77;

    connection.SetupDapper(c => c.ExecuteScalar<int>(It.IsAny<string>(), It.IsAny<object>(), null, null, null))
              .Returns(expected);

    var actual = connection.Object.ExecuteScalar<int>(
        "select * from people where id = @id", new { id = 1 }, null, null);

    Assert.That(actual, Is.EqualTo(expected));
}
```
Stack trace:
```
   at ParamInfo44e2be98-d8bb-4358-8537-1dc2da8dc716(IDbCommand , Object )
   at Dapper.CommandDefinition.SetupCommand(IDbConnection cnn, Action`2 paramReader)
   at Dapper.SqlMapper.ExecuteScalarImpl[T](IDbConnection cnn, CommandDefinition& command)
   at Dapper.SqlMapper.ExecuteScalar[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType)
```

When no parameters are used in the command, it works.

After investigation I found [this](https://weblogs.asp.net/jaimedelpalacio/testing-code-that-uses-dapper-1-10)

It turns out that Dapper internally needs to add parameters to the `IDbCommand.Parameters` collection and this is currently null.

**Comment by UnoSD** [comment]
Thanks for bringing this up, I will have a look at it and merge the PR when I get a chance.

**Comment by UnoSD** [comment]
Merged PR. Thanks.
