### ISSUE TITLE
ExecuteAsync with parameter

### ISSUE THREAD

**Issue by pauloasantos** [UnoSD/Moq.Dapper#25]
I'm using Moq.Dapper for my unit tests, however when i used with parameter, throw exception "Object reference not set to an instance of an object"

Example:
```
var connection = new Mock<DbConnection>();
connection.SetupDapperAsync(c => c.ExecuteAsync(It.IsAny<string>(), It.IsAny<UsuarioInfo>(), It.IsAny<DbTransaction>(), null, null)).ReturnsAsync(0);

await connection.Object.ExecuteAsync("@Login", new { Login = "test"}, null);
```

**Comment by laaladjelouah** [comment]
I have the same problem and this is my stackTrace : 

`StackTrace:	
at ParamInfobbce6ce9-de83-4426-a005-45a32082c57f(IDbCommand , Object )
   at Dapper.CommandDefinition.SetupCommand(IDbConnection cnn, Action`2 paramReader)
   at Dapper.SqlMapper.TrySetupAsyncCommand(CommandDefinition command, IDbConnection cnn, Action`2 paramReader)
   at Dapper.SqlMapper.<ExecuteImplAsync>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at XXX.XXXX.Infrastructure.Data.XXXX.SqlServerRepository.<AddXXXXAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Cds.ModelDefinitions.SqlRepositoryTests.<AddDefinitionDaoTest>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Message du résultat :	System.NullReferenceException : Object reference not set to an instance of an object.`

**Comment by laaladjelouah** [comment]
I have the same problem and this is my StackTrace : 

`at ParamInfobbce6ce9-de83-4426-a005-45a32082c57f(IDbCommand , Object )
   at Dapper.CommandDefinition.SetupCommand(IDbConnection cnn, Action`2 paramReader)
   at Dapper.SqlMapper.TrySetupAsyncCommand(CommandDefinition command, IDbConnection cnn, Action`2 paramReader)
   at Dapper.SqlMapper.<ExecuteImplAsync>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at xxx.Infrastructure.Data.xxxx.SqlServerRepository.<AddxxxAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at xxx.SqlRepositoryTests.<AddxxxTest>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Message du résultat :	System.NullReferenceException : Object reference not set to an instance of an object.
`

**Comment by pauloasantos** [comment]
Hi @laaladjelouah ,

I Used this nuget

https://www.nuget.org/packages/GateCode.Framework.Tests/

and i mock the object:


`DbConnection.Setup(x => x.Connection).Returns(MockDbConnection.InitMock(x => x.ExecuteAsync(It.IsAny<string>(), It.IsAny<UsuarioInfo>(), It.IsAny<DbTransaction>(), null, null)));`

**Comment by max7969** [comment]
Hi,
I have exactly the same problem, is there any correction planned ?
Thank's in advance.

**Comment by pauloasantos** [comment]
I Used this to resolve:

https://github.com/UnoSD/Moq.Dapper/issues/25#issuecomment-425427191

**Comment by UnoSD** [comment]
@pauloasantos feel free to re-add the comment, I deleted it by mistake.

**Comment by max7969** [comment]
I saw the comment but unfortunately I'm limited in the use of external NuGet :(. It's why I was asking if any correction was planned into Moq.Dapper.

**Comment by UnoSD** [comment]
@max7969 I will have some spare time at the end of November, I know it's not really close, but I am the only active contributor. Should be sorted then.

**Comment by max7969** [comment]
@UnoSD Thank's for quick responding, end of the year is perfect ;)

**Comment by aabragan** [comment]
Is this issue resolved yet? I am still getting an error during the setup of the dapper mock. I am running v1.0.0.9. Thanks in advance!
![image](https://user-images.githubusercontent.com/580127/53589569-b5d2d000-3b5d-11e9-93ab-db72e91f685b.png)

**Comment by UnoSD** [comment]
Hi everyone, apologies for not keeping my promise, but I did not manage to get to it yet. I won't make promises again, but if anyone makes a PR I'll jump on it quickly.

**Comment by Al38andr0** [comment]
Same issue and same version as @aabragan. Any update?
Thank you.

**Comment by 1ewallace1** [comment]
I ran into the same issue as @aabragan when using `Mock<IDbConnection>()`. It was resolved when I used `Mock<DbConnection>`.

**Comment by stevieray8450** [comment]
@1ewallace1  -- +1. This workaround also did the trick for me

https://dotnetfiddle.net/a2W4Ih

**Comment by bupdaddy** [comment]
Brilliant lifehack solution. Thanks!
