### ISSUE TITLE
Mocking SqlMapper.QueryFirstOrDefault call is not supported

### ISSUE THREAD

**Issue by derkachdeveloper** [UnoSD/Moq.Dapper#7]
**code**
```
var userPermissions = new RaPermission[0];
var user = new RaUser()
{
    UserId = 1,
    UserEmail = "UserEmail",
    Permissions = userPermissions.ToList()
};

dbMock.SetupDapper(x => x.QueryFirstOrDefault<RaUser>(It.IsAny<string>(), It.IsAny<object>(), null, null, null))
    .Returns(user);
```

**stack trace**

```
   at Moq.Dapper.DbConnectionInterfaceMockExtensions.SetupDapper[TResult](Mock`1 mock, Expression`1 expression)
   at RAPMD.Web.Tests.Auth.UserServiceTests.GetByIdExistsUserTest() in D:\EPAM\RAPMD\source\RAPMD.Web.Tests\Auth\UserServiceTests.cs:line 59
```

![image](https://user-images.githubusercontent.com/6834477/35623321-3bfa9624-069c-11e8-965c-2e9d65fadc16.png)

**Comment by UnoSD** [comment]
Now it is: commit cde564fe1a0fef135111e8a63ae1c25996c7fb8b
